-- =========================================================
-- ARCHIVERSE FULL DATABASE SCHEMA
-- Run this in the Supabase SQL editor.
-- Idempotent: safe to run more than once.
-- =========================================================

create extension if not exists pgcrypto;

-- =========================================================
-- 0) SHARED HELPERS
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

-- =========================================================
-- 1) ARTWORKS
-- =========================================================

create table if not exists public.artworks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  price numeric not null,
  image text,
  images jsonb not null default '[]'::jsonb,
  medium text not null default '',
  size text not null default '',
  status text not null default 'available',
  category text not null default 'canvas',
  is_featured boolean not null default false,
  featured_rank integer,
  quantity integer not null default 1,
  tags text[] not null default '{}',
  instagram_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.artworks
  add column if not exists title text,
  add column if not exists description text not null default '',
  add column if not exists price numeric,
  add column if not exists image text,
  add column if not exists images jsonb not null default '[]'::jsonb,
  add column if not exists medium text not null default '',
  add column if not exists size text not null default '',
  add column if not exists status text not null default 'available',
  add column if not exists category text not null default 'canvas',
  add column if not exists is_featured boolean not null default false,
  add column if not exists featured_rank integer,
  add column if not exists quantity integer not null default 1,
  add column if not exists tags text[] not null default '{}',
  add column if not exists instagram_url text,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

update public.artworks
set
  category = coalesce(nullif(category, ''), 'canvas'),
  status = coalesce(nullif(status, ''), 'available'),
  is_featured = coalesce(is_featured, false),
  quantity = greatest(coalesce(quantity, 1), 0),
  tags = coalesce(tags, '{}');

alter table public.artworks
  alter column category set default 'canvas',
  alter column status set default 'available',
  alter column is_featured set default false,
  alter column quantity set default 1,
  alter column tags set default '{}',
  alter column images set default '[]'::jsonb;

alter table public.artworks
  drop constraint if exists artworks_category_check,
  drop constraint if exists artworks_price_positive,
  drop constraint if exists artworks_status_check,
  drop constraint if exists artworks_quantity_check,
  drop constraint if exists artworks_quantity_positive,
  drop constraint if exists artworks_featured_rank_check;

alter table public.artworks
  add constraint artworks_category_check check (category in ('canvas', 'sketch')),
  add constraint artworks_price_positive check (price > 0),
  add constraint artworks_status_check check (status in ('available', 'sold')),
  add constraint artworks_quantity_check check (quantity >= 0),
  add constraint artworks_featured_rank_check check (featured_rank is null or featured_rank >= 0);

create index if not exists artworks_category_idx on public.artworks(category);
create index if not exists artworks_status_idx on public.artworks(status);
create index if not exists artworks_is_featured_idx on public.artworks(is_featured);
create index if not exists artworks_featured_rank_idx on public.artworks(featured_rank);
create index if not exists artworks_tags_idx on public.artworks using gin(tags);

drop trigger if exists artworks_set_updated_at on public.artworks;
create trigger artworks_set_updated_at
before update on public.artworks
for each row
execute function public.set_updated_at();

create or replace function public.mark_artwork_sold_when_out_of_stock()
returns trigger
language plpgsql
as $$
begin
  if new.quantity <= 0 then
    new.status = 'sold';
  end if;

  return new;
end;
$$;

drop trigger if exists artworks_auto_sold_when_out_of_stock on public.artworks;
create trigger artworks_auto_sold_when_out_of_stock
before insert or update of quantity on public.artworks
for each row
execute function public.mark_artwork_sold_when_out_of_stock();

-- =========================================================
-- 2) ORDERS + PAYMENT LOGS
-- =========================================================

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  order_code text,
  product_id bigint not null,
  product_title text not null,
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  customer_email text not null,
  total_amount numeric not null,
  advance_amount numeric not null,
  payment_status text not null default 'pending',
  payment_provider text not null default 'razorpay',
  razorpay_payment_id text,
  razorpay_order_id text,
  razorpay_signature text,
  payment_verified_at timestamptz,
  processing_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz
);

alter table public.orders
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists order_code text,
  add column if not exists product_id bigint,
  add column if not exists product_title text,
  add column if not exists customer_name text,
  add column if not exists customer_phone text,
  add column if not exists customer_address text,
  add column if not exists customer_email text,
  add column if not exists total_amount numeric,
  add column if not exists advance_amount numeric,
  add column if not exists payment_status text not null default 'pending',
  add column if not exists payment_provider text not null default 'razorpay',
  add column if not exists razorpay_payment_id text,
  add column if not exists razorpay_order_id text,
  add column if not exists razorpay_signature text,
  add column if not exists payment_verified_at timestamptz,
  add column if not exists processing_at timestamptz,
  add column if not exists shipped_at timestamptz,
  add column if not exists delivered_at timestamptz;

update public.orders
set order_code = concat(
  'ARC-',
  extract(year from coalesce(created_at, timezone('utc', now())))::int,
  '-',
  lpad(id::text, 4, '0')
)
where order_code is null;

alter table public.orders
  alter column order_code set not null;

alter table public.orders
  drop constraint if exists orders_total_amount_positive,
  drop constraint if exists orders_advance_amount_positive,
  drop constraint if exists orders_payment_status_check;

alter table public.orders
  add constraint orders_total_amount_positive check (total_amount > 0),
  add constraint orders_advance_amount_positive check (advance_amount > 0),
  add constraint orders_payment_status_check
    check (payment_status in ('pending', 'advance_paid', 'processing', 'shipped', 'delivered', 'fully_paid', 'cancelled'));

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'orders'
      and constraint_name = 'orders_product_id_fkey'
  ) then
    alter table public.orders
      add constraint orders_product_id_fkey
      foreign key (product_id) references public.artworks(id) on delete restrict;
  end if;
end $$;

create unique index if not exists orders_order_code_key on public.orders(order_code);
create unique index if not exists orders_razorpay_payment_id_key
  on public.orders(razorpay_payment_id)
  where razorpay_payment_id is not null;
create index if not exists orders_customer_email_idx on public.orders(lower(customer_email));
create index if not exists orders_payment_status_idx on public.orders(payment_status);
create index if not exists orders_created_at_idx on public.orders(created_at desc);

create or replace function public.prevent_order_immutable_changes()
returns trigger
language plpgsql
as $$
begin
  if new.product_id is distinct from old.product_id then
    raise exception 'product_id cannot be changed after order creation';
  end if;

  if new.total_amount is distinct from old.total_amount then
    raise exception 'total_amount cannot be changed after order creation';
  end if;

  if new.advance_amount is distinct from old.advance_amount then
    raise exception 'advance_amount cannot be changed after order creation';
  end if;

  return new;
end;
$$;

drop trigger if exists lock_order_critical_fields on public.orders;
create trigger lock_order_critical_fields
before update on public.orders
for each row
execute function public.prevent_order_immutable_changes();

create table if not exists public.payment_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  event_type text not null,
  status text not null,
  razorpay_payment_id text,
  razorpay_order_id text,
  order_id bigint references public.orders(id) on delete set null,
  details jsonb not null default '{}'::jsonb
);

create index if not exists payment_logs_payment_id_idx on public.payment_logs(razorpay_payment_id);
create index if not exists payment_logs_order_id_idx on public.payment_logs(order_id);
create index if not exists payment_logs_created_at_idx on public.payment_logs(created_at desc);

-- =========================================================
-- 3) COMMISSIONS
-- =========================================================

create table if not exists public.commissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  name text not null,
  email text not null,
  phone text not null,
  artwork_type text not null,
  size text not null,
  deadline text not null,
  description text not null,
  reference_images jsonb not null default '[]'::jsonb,
  status text not null default 'pending',
  idea_text text,
  structured_brief jsonb not null default '{}'::jsonb,
  clearer_brief text,
  suggested_reply text
);

alter table public.commissions
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists name text,
  add column if not exists email text,
  add column if not exists phone text,
  add column if not exists artwork_type text,
  add column if not exists size text,
  add column if not exists deadline text,
  add column if not exists description text,
  add column if not exists reference_images jsonb not null default '[]'::jsonb,
  add column if not exists status text not null default 'pending',
  add column if not exists idea_text text,
  add column if not exists structured_brief jsonb not null default '{}'::jsonb,
  add column if not exists clearer_brief text,
  add column if not exists suggested_reply text;

do $$
declare
  reference_images_type text;
begin
  select data_type
  into reference_images_type
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'commissions'
    and column_name = 'reference_images';

  if reference_images_type = 'ARRAY' then
    alter table public.commissions
      alter column reference_images type jsonb
      using coalesce(to_jsonb(reference_images), '[]'::jsonb);
  end if;
end $$;

alter table public.commissions
  drop constraint if exists commissions_status_check,
  drop constraint if exists commissions_artwork_type_check;

alter table public.commissions
  add constraint commissions_status_check check (status in ('pending', 'accepted', 'rejected')),
  add constraint commissions_artwork_type_check check (artwork_type in ('canvas', 'sketch'));

create index if not exists commissions_status_idx on public.commissions(status);
create index if not exists commissions_created_at_idx on public.commissions(created_at desc);

-- =========================================================
-- 4) TESTIMONIALS
-- =========================================================

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  name text not null,
  content text not null,
  customer_name text,
  review_text text,
  rating integer not null default 5,
  location text not null default '',
  artwork_id bigint references public.artworks(id) on delete set null,
  is_featured boolean not null default false,
  is_visible boolean not null default true
);

alter table public.testimonials
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists name text,
  add column if not exists content text,
  add column if not exists customer_name text,
  add column if not exists review_text text,
  add column if not exists rating integer not null default 5,
  add column if not exists location text not null default '',
  add column if not exists artwork_id bigint,
  add column if not exists is_featured boolean not null default false,
  add column if not exists is_visible boolean not null default true;

update public.testimonials
set
  name = coalesce(nullif(name, ''), nullif(customer_name, ''), 'Anonymous'),
  content = coalesce(nullif(content, ''), nullif(review_text, ''), 'No review provided.'),
  is_featured = coalesce(is_featured, false),
  is_visible = coalesce(is_visible, true);

alter table public.testimonials
  alter column name set not null,
  alter column content set not null;

alter table public.testimonials
  drop constraint if exists testimonials_rating_check;

alter table public.testimonials
  add constraint testimonials_rating_check check (rating between 1 and 5);

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'testimonials'
      and constraint_name = 'testimonials_artwork_id_fkey'
  ) then
    alter table public.testimonials
      add constraint testimonials_artwork_id_fkey
      foreign key (artwork_id) references public.artworks(id) on delete set null;
  end if;
end $$;

create index if not exists testimonials_created_at_idx on public.testimonials(created_at desc);
create index if not exists testimonials_featured_idx on public.testimonials(is_featured);
create index if not exists testimonials_visible_featured_created_idx
  on public.testimonials(is_visible, is_featured, created_at desc);

-- =========================================================
-- 5) INQUIRIES
-- =========================================================

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null default '',
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.inquiries
  add column if not exists name text,
  add column if not exists email text,
  add column if not exists subject text not null default '',
  add column if not exists message text,
  add column if not exists is_read boolean not null default false,
  add column if not exists created_at timestamptz not null default timezone('utc', now());

create index if not exists inquiries_created_at_idx on public.inquiries(created_at desc);
create index if not exists inquiries_is_read_idx on public.inquiries(is_read, created_at desc);

-- =========================================================
-- 6) CUSTOMER USER ACCOUNTS
-- Fixes: Could not find table public.user_accounts.
-- =========================================================

create table if not exists public.user_accounts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  name text not null,
  email text not null unique,
  password_hash text not null
);

alter table public.user_accounts
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now()),
  add column if not exists name text,
  add column if not exists email text,
  add column if not exists password_hash text;

create unique index if not exists user_accounts_email_key on public.user_accounts(email);
create index if not exists user_accounts_email_idx on public.user_accounts(lower(email));

drop trigger if exists user_accounts_set_updated_at on public.user_accounts;
create trigger user_accounts_set_updated_at
before update on public.user_accounts
for each row
execute function public.set_updated_at();

-- =========================================================
-- 7) ADMIN SYSTEM
-- Current backend expects bigint ids and action_type columns.
-- =========================================================

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'admin',
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.admins
  add column if not exists name text,
  add column if not exists email text,
  add column if not exists password_hash text,
  add column if not exists role text not null default 'admin',
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

create unique index if not exists admins_email_key on public.admins(email);
create index if not exists admins_email_idx on public.admins(lower(email));

drop trigger if exists admins_set_updated_at on public.admins;
create trigger admins_set_updated_at
before update on public.admins
for each row
execute function public.set_updated_at();

create table if not exists public.admin_sessions (
  id bigint generated by default as identity primary key,
  admin_id bigint not null references public.admins(id) on delete cascade,
  session_token_id uuid not null unique,
  email text not null,
  name text not null,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz not null default timezone('utc', now()),
  logged_out_at timestamptz
);

alter table public.admin_sessions
  add column if not exists admin_id bigint,
  add column if not exists session_token_id uuid,
  add column if not exists email text,
  add column if not exists name text,
  add column if not exists ip_address text,
  add column if not exists user_agent text,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists last_seen_at timestamptz not null default timezone('utc', now()),
  add column if not exists logged_out_at timestamptz;

create unique index if not exists admin_sessions_token_key on public.admin_sessions(session_token_id);
create index if not exists admin_sessions_admin_id_idx on public.admin_sessions(admin_id, created_at desc);
create index if not exists admin_sessions_token_idx on public.admin_sessions(session_token_id);

create table if not exists public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  admin_id bigint references public.admins(id) on delete set null,
  admin_session_id bigint references public.admin_sessions(id) on delete set null,
  admin_name text not null default '',
  admin_email text not null default '',
  action_type text not null,
  resource_type text not null default 'system',
  resource_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.admin_activity_logs
  add column if not exists admin_id bigint,
  add column if not exists admin_session_id bigint,
  add column if not exists admin_name text not null default '',
  add column if not exists admin_email text not null default '',
  add column if not exists action_type text,
  add column if not exists resource_type text not null default 'system',
  add column if not exists resource_id text,
  add column if not exists details jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default timezone('utc', now());

-- Compatibility for older manually-created tables that used action/entity names.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'admin_activity_logs'
      and column_name = 'action'
  ) then
    execute $sql$
      update public.admin_activity_logs
      set action_type = coalesce(action_type, action)
    $sql$;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'admin_activity_logs'
      and column_name = 'entity'
  ) then
    execute $sql$
      update public.admin_activity_logs
      set resource_type = coalesce(nullif(resource_type, ''), entity, 'system')
    $sql$;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'admin_activity_logs'
      and column_name = 'entity_id'
  ) then
    execute $sql$
      update public.admin_activity_logs
      set resource_id = coalesce(resource_id, entity_id::text)
    $sql$;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'admin_activity_logs'
      and column_name = 'metadata'
  ) then
    execute $sql$
      update public.admin_activity_logs
      set details = coalesce(details, metadata, '{}'::jsonb)
    $sql$;
  end if;
end $$;

update public.admin_activity_logs
set
  action_type = coalesce(action_type, 'admin_activity'),
  resource_type = coalesce(nullif(resource_type, ''), 'system'),
  details = coalesce(details, '{}'::jsonb);

alter table public.admin_activity_logs
  alter column action_type set not null,
  alter column resource_type set not null,
  alter column details set not null;

create index if not exists admin_activity_logs_admin_id_idx
  on public.admin_activity_logs(admin_id, created_at desc);
create index if not exists admin_activity_logs_created_at_idx
  on public.admin_activity_logs(created_at desc);
create index if not exists admin_activity_logs_action_type_idx
  on public.admin_activity_logs(action_type);

-- =========================================================
-- 8) ANALYTICS EVENTS
-- =========================================================

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  timestamp timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  metadata jsonb not null default '{}'::jsonb
);

alter table public.analytics_events
  add column if not exists event_type text,
  add column if not exists timestamp timestamptz not null default timezone('utc', now()),
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists metadata jsonb not null default '{}'::jsonb;

update public.analytics_events
set
  created_at = coalesce(created_at, timestamp, timezone('utc', now())),
  timestamp = coalesce(timestamp, created_at, timezone('utc', now())),
  metadata = coalesce(metadata, '{}'::jsonb);

create index if not exists analytics_events_event_type_idx on public.analytics_events(event_type);
create index if not exists analytics_events_type_idx on public.analytics_events(event_type);
create index if not exists analytics_events_timestamp_idx on public.analytics_events(timestamp desc);
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);

-- =========================================================
-- 9) VISITOR TASTE / BEHAVIOR TRACKING
-- =========================================================

create table if not exists public.visitor_sessions (
  session_id text primary key,
  started_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  last_seen timestamptz not null default timezone('utc', now()),
  user_agent text,
  referrer text,
  landing_path text,
  last_path text,
  taste_profile jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.visitor_sessions
  add column if not exists started_at timestamptz not null default timezone('utc', now()),
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists last_seen timestamptz not null default timezone('utc', now()),
  add column if not exists user_agent text,
  add column if not exists referrer text,
  add column if not exists landing_path text,
  add column if not exists last_path text,
  add column if not exists taste_profile jsonb not null default '{}'::jsonb,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  session_id text not null references public.visitor_sessions(session_id) on delete cascade,
  event_type text not null,
  artwork_id bigint references public.artworks(id) on delete set null,
  path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.visitor_events
  add column if not exists session_id text,
  add column if not exists event_type text,
  add column if not exists artwork_id bigint,
  add column if not exists path text,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default timezone('utc', now());

alter table public.visitor_events
  drop constraint if exists visitor_events_event_type_check;

alter table public.visitor_events
  add constraint visitor_events_event_type_check
  check (
    event_type in (
      'artwork_view',
      'artwork_click',
      'product_open',
      'instagram_click',
      'commission_open',
      'search_query',
      'hover_dwell',
      'combo_click',
      'checkout_started',
      'order_completed',
      'purchase',
      'recommendation_reset'
    )
  );

create index if not exists visitor_events_session_id_idx on public.visitor_events(session_id);
create index if not exists visitor_events_event_type_idx on public.visitor_events(event_type);
create index if not exists visitor_events_created_at_idx on public.visitor_events(created_at desc);
create index if not exists visitor_events_artwork_id_idx on public.visitor_events(artwork_id);

create table if not exists public.visitor_taste_profiles (
  session_id text primary key references public.visitor_sessions(session_id) on delete cascade,
  taste_profile jsonb not null default '{}'::jsonb,
  profile jsonb not null default '{}'::jsonb,
  last_seen timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.visitor_taste_profiles
  add column if not exists taste_profile jsonb not null default '{}'::jsonb,
  add column if not exists profile jsonb not null default '{}'::jsonb,
  add column if not exists last_seen timestamptz not null default timezone('utc', now()),
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

create index if not exists visitor_taste_profiles_last_seen_idx
  on public.visitor_taste_profiles(last_seen desc);
create index if not exists visitor_taste_profiles_updated_at_idx
  on public.visitor_taste_profiles(updated_at desc);

drop trigger if exists visitor_taste_profiles_set_updated_at on public.visitor_taste_profiles;
create trigger visitor_taste_profiles_set_updated_at
before update on public.visitor_taste_profiles
for each row
execute function public.set_updated_at();

-- =========================================================
-- 10) COMBOS
-- =========================================================

create table if not exists public.combos (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  artwork_ids bigint[] not null,
  discount_percent integer not null default 10,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.combos
  add column if not exists title text,
  add column if not exists artwork_ids bigint[] not null default '{}',
  add column if not exists discount_percent integer not null default 10,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default timezone('utc', now());

alter table public.combos
  drop constraint if exists combos_discount_percent_check,
  drop constraint if exists combos_artwork_count_check;

alter table public.combos
  add constraint combos_discount_percent_check
    check (discount_percent >= 0 and discount_percent <= 50),
  add constraint combos_artwork_count_check
    check (array_length(artwork_ids, 1) between 2 and 5);

create index if not exists combos_is_active_idx on public.combos(is_active);
create index if not exists combos_active_idx on public.combos(is_active);

-- =========================================================
-- 11) STOCK + COMBO FUNCTIONS
-- =========================================================

create or replace function public.decrement_artwork_stock(_artwork_ids bigint[])
returns void
language plpgsql
as $$
declare
  aid bigint;
  current_qty integer;
begin
  for aid in select unnest(_artwork_ids)
  loop
    select quantity
    into current_qty
    from public.artworks
    where id = aid
    for update;

    if current_qty is null then
      raise exception 'artwork % not found', aid;
    end if;

    if current_qty <= 0 then
      raise exception 'artwork % is out of stock', aid;
    end if;
  end loop;

  update public.artworks
  set quantity = quantity - 1
  where id = any(_artwork_ids);
end;
$$;

create or replace function public.validate_combo_artworks(_artwork_ids bigint[])
returns void
language plpgsql
as $$
declare
  total_count integer;
  distinct_count integer;
begin
  total_count := coalesce(array_length(_artwork_ids, 1), 0);

  if total_count < 2 or total_count > 5 then
    raise exception 'combo must have between 2 and 5 artworks';
  end if;

  select count(distinct x)
  into distinct_count
  from unnest(_artwork_ids) as x;

  if total_count != distinct_count then
    raise exception 'duplicate artworks in combo not allowed';
  end if;
end;
$$;

-- =========================================================
-- 12) STORAGE BUCKETS
-- =========================================================

insert into storage.buckets (id, name, public)
values
  ('artworks', 'artworks', true),
  ('commission-references', 'commission-references', true)
on conflict (id) do update set public = excluded.public;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Public can view artwork images'
  ) then
    create policy "Public can view artwork images"
    on storage.objects
    for select
    to public
    using (bucket_id = 'artworks');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Public can view commission reference images'
  ) then
    create policy "Public can view commission reference images"
    on storage.objects
    for select
    to public
    using (bucket_id = 'commission-references');
  end if;
end $$;

-- =========================================================
-- 13) ROW LEVEL SECURITY
-- Serverless API uses service role. These policies avoid exposing
-- admin/customer tables directly to public browser clients.
-- =========================================================

alter table public.artworks enable row level security;
alter table public.testimonials enable row level security;
alter table public.commissions enable row level security;
alter table public.inquiries enable row level security;
alter table public.user_accounts enable row level security;
alter table public.admins enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.admin_activity_logs enable row level security;
alter table public.visitor_sessions enable row level security;
alter table public.visitor_events enable row level security;
alter table public.visitor_taste_profiles enable row level security;

drop policy if exists "public_read_artworks" on public.artworks;
create policy "public_read_artworks"
on public.artworks
for select
to anon, authenticated
using (true);

drop policy if exists "public_read_visible_testimonials" on public.testimonials;
create policy "public_read_visible_testimonials"
on public.testimonials
for select
to anon, authenticated
using (is_visible = true);

drop policy if exists "no_public_user_accounts" on public.user_accounts;
create policy "no_public_user_accounts"
on public.user_accounts
for all
to anon, authenticated
using (false)
with check (false);

drop policy if exists "no_public_admins" on public.admins;
create policy "no_public_admins"
on public.admins
for all
to anon, authenticated
using (false)
with check (false);

drop policy if exists "no_public_admin_sessions" on public.admin_sessions;
create policy "no_public_admin_sessions"
on public.admin_sessions
for all
to anon, authenticated
using (false)
with check (false);

drop policy if exists "no_public_admin_activity_logs" on public.admin_activity_logs;
create policy "no_public_admin_activity_logs"
on public.admin_activity_logs
for all
to anon, authenticated
using (false)
with check (false);

-- =========================================================
-- 14) POSTGREST SCHEMA CACHE REFRESH
-- Helps Supabase REST stop saying newly-created tables/columns are missing.
-- =========================================================

notify pgrst, 'reload schema';
