-- =============================================================
-- Archiverse — consolidated PENDING migrations (run once)
-- Generated 2026-07-16. Safe/idempotent: uses IF [NOT] EXISTS.
-- Paste into Supabase → SQL Editor → Run, OR psql $DB_URL -f this.
-- =============================================================


-- ─────────────────────────────────────────────────────────────
-- 20260422_archiverse_artwork_stock.sql
-- ─────────────────────────────────────────────────────────────
alter table public.artworks
  add column if not exists quantity integer not null default 1;

update public.artworks
set quantity = 0
where status = 'sold'
  and quantity <> 0;

alter table public.artworks
  drop constraint if exists artworks_quantity_check;

alter table public.artworks
  add constraint artworks_quantity_check
  check (quantity >= 0);

create or replace function public.mark_artwork_sold_when_out_of_stock()
returns trigger
language plpgsql
as $$
begin
  if new.quantity <= 0 then
    new.status = 'sold';
  end if;

  return new;
end;
$$;

drop trigger if exists artworks_auto_sold_when_out_of_stock on public.artworks;

create trigger artworks_auto_sold_when_out_of_stock
before insert or update of quantity on public.artworks
for each row
execute function public.mark_artwork_sold_when_out_of_stock();

-- ─────────────────────────────────────────────────────────────
-- 20260428_archiverse_commission_briefs.sql
-- ─────────────────────────────────────────────────────────────
alter table if exists public.commissions
  add column if not exists idea_text text,
  add column if not exists structured_brief jsonb not null default '{}'::jsonb,
  add column if not exists clearer_brief text,
  add column if not exists suggested_reply text;

-- ─────────────────────────────────────────────────────────────
-- 20260528_archiverse_ai_studio_tag_registry.sql
-- ─────────────────────────────────────────────────────────────
create table if not exists public.tag_registry (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type text not null,
  usage_count integer not null default 0,
  created_by text,
  created_at timestamptz not null default timezone('utc', now()),
  is_system boolean not null default false,
  is_active boolean not null default true
);

alter table if exists public.tag_registry
  drop constraint if exists tag_registry_type_check;

alter table if exists public.tag_registry
  add constraint tag_registry_type_check
  check (type in ('style', 'mood', 'color', 'subject', 'space', 'energy', 'medium', 'collection'));

create index if not exists tag_registry_type_idx
  on public.tag_registry(type, usage_count desc);

create index if not exists tag_registry_active_idx
  on public.tag_registry(is_active, usage_count desc);

-- ─────────────────────────────────────────────────────────────
-- 20260528_archiverse_google_oauth_user_analytics.sql
-- ─────────────────────────────────────────────────────────────
alter table if exists public.user_accounts
  add column if not exists provider text not null default 'email',
  add column if not exists google_id text,
  add column if not exists avatar_url text,
  add column if not exists last_login_at timestamptz,
  add column if not exists login_count integer not null default 0,
  add column if not exists welcome_email_sent boolean not null default false;

alter table if exists public.user_accounts
  add constraint user_accounts_provider_check
  check (provider in ('email', 'google', 'email+google'));

create unique index if not exists user_accounts_google_id_idx
  on public.user_accounts(google_id)
  where google_id is not null;

create table if not exists public.user_login_events (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  provider text not null,
  login_at timestamptz not null default timezone('utc', now()),
  ip_address text,
  user_agent text
);

alter table if exists public.user_login_events
  add constraint user_login_events_provider_check
  check (provider in ('email', 'google'));

create index if not exists user_login_events_user_id_idx
  on public.user_login_events(user_id, login_at desc);

create index if not exists user_login_events_provider_idx
  on public.user_login_events(provider, login_at desc);

alter table if exists public.visitor_events
  add column if not exists user_id bigint references public.user_accounts(id) on delete set null;

create index if not exists visitor_events_user_id_idx
  on public.visitor_events(user_id, created_at desc);

create table if not exists public.user_taste_profiles (
  user_id bigint primary key references public.user_accounts(id) on delete cascade,
  taste_profile jsonb not null default '{}'::jsonb,
  source_session_ids text[] not null default '{}'::text[],
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists user_taste_profiles_updated_at_idx
  on public.user_taste_profiles(updated_at desc);

-- ─────────────────────────────────────────────────────────────
-- 20260528_archiverse_identity_retention_personalization.sql
-- ─────────────────────────────────────────────────────────────
create table if not exists public.user_saved_artworks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  artwork_id bigint not null references public.artworks(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique(user_id, artwork_id)
);

create index if not exists user_saved_artworks_user_id_idx
  on public.user_saved_artworks(user_id, created_at desc);

create index if not exists user_saved_artworks_artwork_id_idx
  on public.user_saved_artworks(artwork_id, created_at desc);

alter table if exists public.user_accounts
  add column if not exists digest_opt_in boolean not null default false,
  add column if not exists digest_frequency text not null default 'weekly',
  add column if not exists digest_last_sent_at timestamptz,
  add column if not exists deleted_at timestamptz;

alter table if exists public.user_accounts
  drop constraint if exists user_accounts_digest_frequency_check;

alter table if exists public.user_accounts
  add constraint user_accounts_digest_frequency_check
  check (digest_frequency in ('weekly', 'biweekly', 'monthly'));

alter table if exists public.analytics_events
  drop constraint if exists analytics_events_event_type_check;

alter table if exists public.analytics_events
  add constraint analytics_events_event_type_check
  check (
    event_type in (
      'artwork_view',
      'artwork_click',
      'product_open',
      'instagram_click',
      'commission_open',
      'search_query',
      'checkout_started',
      'order_completed',
      'recommendation_shown',
      'recommendation_clicked',
      'recommendation_purchased',
      'recommendation_ignored',
      'favorite_added',
      'favorite_removed'
    )
  );

alter table if exists public.visitor_events
  drop constraint if exists visitor_events_event_type_check;

alter table if exists public.visitor_events
  add constraint visitor_events_event_type_check
  check (
    event_type in (
      'artwork_view',
      'artwork_click',
      'product_open',
      'instagram_click',
      'commission_open',
      'search_query',
      'checkout_started',
      'order_completed',
      'recommendation_shown',
      'recommendation_clicked',
      'recommendation_purchased',
      'recommendation_ignored',
      'favorite_added',
      'favorite_removed'
    )
  );

-- ─────────────────────────────────────────────────────────────
-- 20260528_archiverse_refinement_governance_collections.sql
-- ─────────────────────────────────────────────────────────────
create table if not exists public.tag_aliases (
  id bigint generated by default as identity primary key,
  alias text not null unique,
  canonical_tag_id bigint not null references public.tag_registry(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists tag_aliases_canonical_tag_id_idx
  on public.tag_aliases(canonical_tag_id);

create table if not exists public.admin_ai_feedback (
  id bigint generated by default as identity primary key,
  feedback_type text not null,
  source text not null,
  signal_key text not null,
  accepted_count integer not null default 0,
  rejected_count integer not null default 0,
  edited_count integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now()),
  unique(feedback_type, source, signal_key)
);

create table if not exists public.user_collections (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique(user_id, name)
);

create table if not exists public.user_collection_artworks (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.user_collections(id) on delete cascade,
  artwork_id bigint references public.artworks(id) on delete cascade,
  combo_id uuid references public.combos(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  check (artwork_id is not null or combo_id is not null)
);

create index if not exists user_collection_artworks_collection_id_idx
  on public.user_collection_artworks(collection_id, created_at desc);

alter table if exists public.analytics_events
  drop constraint if exists analytics_events_event_type_check;

alter table if exists public.analytics_events
  add constraint analytics_events_event_type_check
  check (
    event_type in (
      'artwork_view',
      'artwork_click',
      'product_open',
      'instagram_click',
      'commission_open',
      'search_query',
      'checkout_started',
      'order_completed',
      'recommendation_shown',
      'recommendation_clicked',
      'recommendation_saved',
      'recommendation_ignored',
      'recommendation_purchased',
      'recommendation_revisited',
      'favorite_added',
      'favorite_removed'
    )
  );

alter table if exists public.visitor_events
  drop constraint if exists visitor_events_event_type_check;

alter table if exists public.visitor_events
  add constraint visitor_events_event_type_check
  check (
    event_type in (
      'artwork_view',
      'artwork_click',
      'product_open',
      'instagram_click',
      'commission_open',
      'search_query',
      'checkout_started',
      'order_completed',
      'recommendation_shown',
      'recommendation_clicked',
      'recommendation_saved',
      'recommendation_ignored',
      'recommendation_purchased',
      'recommendation_revisited',
      'favorite_added',
      'favorite_removed'
    )
  );

-- ─────────────────────────────────────────────────────────────
-- 20260531_archiverse_room_matching.sql
-- ─────────────────────────────────────────────────────────────
create table if not exists public.user_room_profiles (
  id bigserial primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  label text not null default 'My Space',
  space_type text null,
  room_personality text not null default '',
  profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_room_profiles_space_type_check
    check (
      space_type is null
      or space_type in ('bedroom', 'workspace', 'living_room', 'studio', 'gaming_setup')
    )
);

create index if not exists user_room_profiles_user_id_idx
  on public.user_room_profiles(user_id, updated_at desc);

alter table if exists public.analytics_events
  drop constraint if exists analytics_events_event_type_check;

alter table if exists public.analytics_events
  add constraint analytics_events_event_type_check
  check (
    event_type in (
      'artwork_view',
      'artwork_click',
      'product_open',
      'instagram_click',
      'commission_open',
      'search_query',
      'checkout_started',
      'order_completed',
      'recommendation_shown',
      'recommendation_clicked',
      'recommendation_saved',
      'recommendation_ignored',
      'recommendation_purchased',
      'recommendation_revisited',
      'favorite_added',
      'favorite_removed',
      'room_upload',
      'room_analysis_completed',
      'room_personality_detected',
      'room_match_clicked',
      'room_preview_opened',
      'room_profile_saved',
      'room_set_clicked'
    )
  );

alter table if exists public.visitor_events
  drop constraint if exists visitor_events_event_type_check;

alter table if exists public.visitor_events
  add constraint visitor_events_event_type_check
  check (
    event_type in (
      'artwork_view',
      'artwork_click',
      'product_open',
      'instagram_click',
      'commission_open',
      'search_query',
      'checkout_started',
      'order_completed',
      'recommendation_shown',
      'recommendation_clicked',
      'recommendation_saved',
      'recommendation_ignored',
      'recommendation_purchased',
      'recommendation_revisited',
      'favorite_added',
      'favorite_removed',
      'room_upload',
      'room_analysis_completed',
      'room_personality_detected',
      'room_match_clicked',
      'room_preview_opened',
      'room_profile_saved',
      'room_set_clicked'
    )
  );

-- ─────────────────────────────────────────────────────────────
-- 20260716_archiverse_rate_limit_and_reset_tokens.sql
-- ─────────────────────────────────────────────────────────────
-- Persistent, serverless-safe rate limiting + admin password reset tokens.
-- In-memory Maps do not survive across Vercel function instances, so both
-- brute-force protection and the reset flow are backed by the database here.

-- ── Rate limiting ─────────────────────────────────────────────────────────
create table if not exists public.rate_limits (
  bucket_key text primary key,
  count integer not null default 0,
  reset_at timestamptz not null,
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists rate_limits_reset_at_idx on public.rate_limits (reset_at);

-- Atomic "consume one token" for a fixed window. Returns whether the request
-- is allowed plus how long until the window resets. Race-safe via upsert.
create or replace function public.consume_rate_limit(
  p_key text,
  p_limit integer,
  p_window_ms bigint
)
returns table (allowed boolean, remaining integer, retry_after_seconds integer)
language plpgsql
as $$
declare
  v_now timestamptz := timezone('utc', now());
  v_count integer;
  v_reset_at timestamptz;
begin
  insert into public.rate_limits as rl (bucket_key, count, reset_at, updated_at)
  values (p_key, 1, v_now + make_interval(secs => p_window_ms / 1000.0), v_now)
  on conflict (bucket_key) do update
    set count = case
                  when rl.reset_at <= v_now then 1
                  else rl.count + 1
                end,
        reset_at = case
                     when rl.reset_at <= v_now
                       then v_now + make_interval(secs => p_window_ms / 1000.0)
                     else rl.reset_at
                   end,
        updated_at = v_now
  returning rl.count, rl.reset_at into v_count, v_reset_at;

  allowed := v_count <= p_limit;
  remaining := greatest(p_limit - v_count, 0);
  retry_after_seconds := greatest(ceil(extract(epoch from (v_reset_at - v_now)))::integer, 1);
  return next;
end;
$$;

-- ── Admin password reset tokens ───────────────────────────────────────────
-- Only the SHA-256 hash of the token is stored; the plaintext is emailed once.
create table if not exists public.admin_password_reset_tokens (
  id bigserial primary key,
  token_hash text not null unique,
  admin_email text not null,
  admin_id bigint,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists admin_reset_tokens_hash_idx on public.admin_password_reset_tokens (token_hash);
create index if not exists admin_reset_tokens_expires_idx on public.admin_password_reset_tokens (expires_at);

-- Lock everything to the service role (server-side only); no client access.
alter table public.rate_limits enable row level security;
alter table public.admin_password_reset_tokens enable row level security;

drop policy if exists "rate_limits_service_role_only" on public.rate_limits;
create policy "rate_limits_service_role_only"
on public.rate_limits for all to authenticated using (false) with check (false);

drop policy if exists "admin_reset_tokens_service_role_only" on public.admin_password_reset_tokens;
create policy "admin_reset_tokens_service_role_only"
on public.admin_password_reset_tokens for all to authenticated using (false) with check (false);
