let manifestPromise = null

/** Cached fetch of the AR asset manifest generated by build-ar-assets.mjs. */
export function fetchArManifest() {
  if (!manifestPromise) {
    manifestPromise = fetch('/ar/manifest.json')
      .then((response) => (response.ok ? response.json() : {}))
      .catch(() => ({}))
  }
  return manifestPromise
}

export async function getArAssetsForArtwork(artworkId) {
  const manifest = await fetchArManifest()
  return manifest?.[String(artworkId)] || null
}

/**
 * iOS Safari does not support WebXR AR; iPadOS reports itself as "MacIntel"
 * with touch support, which is the standard way to distinguish it from a
 * real Mac.
 */
export function isIOS() {
  if (typeof navigator === 'undefined') {
    return false
  }
  const ua = navigator.userAgent || ''
  const isAppleTouch = /iPad|iPhone|iPod/.test(ua)
  const isIpadOS = navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1
  return isAppleTouch || isIpadOS
}

export function isAndroid() {
  return typeof navigator !== 'undefined' && /Android/.test(navigator.userAgent || '')
}

/**
 * A device that can actually launch camera AR: iOS (AR Quick Look) or Android
 * (Scene Viewer / WebXR — both handled natively by <model-viewer>). Desktop
 * gets the interactive 3D preview and a QR code to continue on a phone.
 */
export function isArCapableDevice() {
  return isIOS() || isAndroid()
}

/** Absolute URL for the current artwork page, used for the desktop→phone QR. */
export function currentPageUrl() {
  if (typeof window === 'undefined') {
    return ''
  }
  return window.location.href
}
