create table if not exists public.tag_aliases (
  id bigint generated by default as identity primary key,
  alias text not null unique,
  canonical_tag_id bigint not null references public.tag_registry(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists tag_aliases_canonical_tag_id_idx
  on public.tag_aliases(canonical_tag_id);

create table if not exists public.admin_ai_feedback (
  id bigint generated by default as identity primary key,
  feedback_type text not null,
  source text not null,
  signal_key text not null,
  accepted_count integer not null default 0,
  rejected_count integer not null default 0,
  edited_count integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now()),
  unique(feedback_type, source, signal_key)
);

create table if not exists public.user_collections (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique(user_id, name)
);

create table if not exists public.user_collection_artworks (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.user_collections(id) on delete cascade,
  artwork_id bigint references public.artworks(id) on delete cascade,
  combo_id uuid references public.combos(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  check (artwork_id is not null or combo_id is not null)
);

create index if not exists user_collection_artworks_collection_id_idx
  on public.user_collection_artworks(collection_id, created_at desc);

alter table if exists public.analytics_events
  drop constraint if exists analytics_events_event_type_check;

alter table if exists public.analytics_events
  add constraint analytics_events_event_type_check
  check (
    event_type in (
      'artwork_view',
      'artwork_click',
      'product_open',
      'instagram_click',
      'commission_open',
      'search_query',
      'checkout_started',
      'order_completed',
      'recommendation_shown',
      'recommendation_clicked',
      'recommendation_saved',
      'recommendation_ignored',
      'recommendation_purchased',
      'recommendation_revisited',
      'favorite_added',
      'favorite_removed'
    )
  );

alter table if exists public.visitor_events
  drop constraint if exists visitor_events_event_type_check;

alter table if exists public.visitor_events
  add constraint visitor_events_event_type_check
  check (
    event_type in (
      'artwork_view',
      'artwork_click',
      'product_open',
      'instagram_click',
      'commission_open',
      'search_query',
      'checkout_started',
      'order_completed',
      'recommendation_shown',
      'recommendation_clicked',
      'recommendation_saved',
      'recommendation_ignored',
      'recommendation_purchased',
      'recommendation_revisited',
      'favorite_added',
      'favorite_removed'
    )
  );
