create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  customer_name text not null,
  review_text text not null,
  rating integer not null default 5,
  location text not null default '',
  is_visible boolean not null default true,
  constraint testimonials_rating_check check (rating between 1 and 5)
);

create index if not exists testimonials_visible_created_idx
  on public.testimonials (is_visible, created_at desc);
