create table if not exists public.commissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  name text not null,
  email text not null,
  phone text not null,
  artwork_type text not null,
  size text not null,
  deadline text not null,
  description text not null,
  reference_images jsonb not null default '[]'::jsonb,
  status text not null default 'pending'
);

alter table public.commissions
  drop constraint if exists commissions_status_check;

alter table public.commissions
  add constraint commissions_status_check
  check (status in ('pending', 'accepted', 'rejected'));

alter table public.commissions
  drop constraint if exists commissions_artwork_type_check;

alter table public.commissions
  add constraint commissions_artwork_type_check
  check (artwork_type in ('canvas', 'sketch'));

insert into storage.buckets (id, name, public)
values ('commission-references', 'commission-references', true)
on conflict (id) do update set public = excluded.public;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Public can view commission reference images'
  ) then
    create policy "Public can view commission reference images"
      on storage.objects
      for select
      to public
      using (bucket_id = 'commission-references');
  end if;
end $$;
