create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  timestamp timestamptz not null default timezone('utc', now()),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists analytics_events_event_type_idx
  on public.analytics_events(event_type);

create index if not exists analytics_events_timestamp_idx
  on public.analytics_events(timestamp desc);
