alter table if exists public.artworks
  add column if not exists tags text[] not null default '{}',
  add column if not exists instagram_url text,
  add column if not exists featured_rank integer;

alter table if exists public.artworks
  drop constraint if exists artworks_featured_rank_check;

alter table if exists public.artworks
  add constraint artworks_featured_rank_check
  check (featured_rank is null or featured_rank >= 0);

create table if not exists public.visitor_sessions (
  session_id text primary key,
  started_at timestamptz not null default timezone('utc', now()),
  last_seen timestamptz not null default timezone('utc', now()),
  user_agent text,
  referrer text,
  landing_path text,
  last_path text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  session_id text not null references public.visitor_sessions(session_id) on delete cascade,
  event_type text not null,
  artwork_id bigint references public.artworks(id) on delete set null,
  path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

alter table if exists public.visitor_events
  drop constraint if exists visitor_events_event_type_check;

alter table if exists public.visitor_events
  add constraint visitor_events_event_type_check
  check (
    event_type in (
      'artwork_view',
      'artwork_click',
      'product_open',
      'instagram_click',
      'commission_open',
      'search_query',
      'checkout_started',
      'order_completed'
    )
  );

create index if not exists visitor_events_session_id_idx
  on public.visitor_events(session_id);

create index if not exists visitor_events_event_type_idx
  on public.visitor_events(event_type);

create index if not exists visitor_events_created_at_idx
  on public.visitor_events(created_at desc);

create table if not exists public.visitor_taste_profiles (
  session_id text primary key references public.visitor_sessions(session_id) on delete cascade,
  taste_profile jsonb not null default '{}'::jsonb,
  last_seen timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists visitor_taste_profiles_last_seen_idx
  on public.visitor_taste_profiles(last_seen desc);
