alter table public.orders
  add column if not exists processing_at timestamptz,
  add column if not exists shipped_at timestamptz,
  add column if not exists delivered_at timestamptz;

alter table public.orders
  drop constraint if exists orders_payment_status_check;

alter table public.orders
  add constraint orders_payment_status_check
  check (payment_status in ('pending', 'advance_paid', 'processing', 'shipped', 'delivered', 'cancelled'));

create table if not exists public.payment_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  event_type text not null,
  status text not null,
  razorpay_payment_id text,
  razorpay_order_id text,
  order_id bigint references public.orders(id) on delete set null,
  details jsonb not null default '{}'::jsonb
);

create index if not exists payment_logs_payment_id_idx
  on public.payment_logs(razorpay_payment_id);

create index if not exists payment_logs_order_id_idx
  on public.payment_logs(order_id);
