create table if not exists public.user_saved_artworks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  artwork_id bigint not null references public.artworks(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique(user_id, artwork_id)
);

create index if not exists user_saved_artworks_user_id_idx
  on public.user_saved_artworks(user_id, created_at desc);

create index if not exists user_saved_artworks_artwork_id_idx
  on public.user_saved_artworks(artwork_id, created_at desc);

alter table if exists public.user_accounts
  add column if not exists digest_opt_in boolean not null default false,
  add column if not exists digest_frequency text not null default 'weekly',
  add column if not exists digest_last_sent_at timestamptz,
  add column if not exists deleted_at timestamptz;

alter table if exists public.user_accounts
  drop constraint if exists user_accounts_digest_frequency_check;

alter table if exists public.user_accounts
  add constraint user_accounts_digest_frequency_check
  check (digest_frequency in ('weekly', 'biweekly', 'monthly'));

alter table if exists public.analytics_events
  drop constraint if exists analytics_events_event_type_check;

alter table if exists public.analytics_events
  add constraint analytics_events_event_type_check
  check (
    event_type in (
      'artwork_view',
      'artwork_click',
      'product_open',
      'instagram_click',
      'commission_open',
      'search_query',
      'checkout_started',
      'order_completed',
      'recommendation_shown',
      'recommendation_clicked',
      'recommendation_purchased',
      'recommendation_ignored',
      'favorite_added',
      'favorite_removed'
    )
  );

alter table if exists public.visitor_events
  drop constraint if exists visitor_events_event_type_check;

alter table if exists public.visitor_events
  add constraint visitor_events_event_type_check
  check (
    event_type in (
      'artwork_view',
      'artwork_click',
      'product_open',
      'instagram_click',
      'commission_open',
      'search_query',
      'checkout_started',
      'order_completed',
      'recommendation_shown',
      'recommendation_clicked',
      'recommendation_purchased',
      'recommendation_ignored',
      'favorite_added',
      'favorite_removed'
    )
  );
