create table if not exists public.tag_registry (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type text not null,
  usage_count integer not null default 0,
  created_by text,
  created_at timestamptz not null default timezone('utc', now()),
  is_system boolean not null default false,
  is_active boolean not null default true
);

alter table if exists public.tag_registry
  drop constraint if exists tag_registry_type_check;

alter table if exists public.tag_registry
  add constraint tag_registry_type_check
  check (type in ('style', 'mood', 'color', 'subject', 'space', 'energy', 'medium', 'collection'));

create index if not exists tag_registry_type_idx
  on public.tag_registry(type, usage_count desc);

create index if not exists tag_registry_active_idx
  on public.tag_registry(is_active, usage_count desc);
