create table if not exists public.user_accounts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  name text not null,
  email text not null unique,
  password_hash text not null
);

create index if not exists user_accounts_email_idx
  on public.user_accounts (lower(email));
