alter table if exists public.user_accounts
  add column if not exists provider text not null default 'email',
  add column if not exists google_id text,
  add column if not exists avatar_url text,
  add column if not exists last_login_at timestamptz,
  add column if not exists login_count integer not null default 0,
  add column if not exists welcome_email_sent boolean not null default false;

alter table if exists public.user_accounts
  add constraint user_accounts_provider_check
  check (provider in ('email', 'google', 'email+google'));

create unique index if not exists user_accounts_google_id_idx
  on public.user_accounts(google_id)
  where google_id is not null;

create table if not exists public.user_login_events (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  provider text not null,
  login_at timestamptz not null default timezone('utc', now()),
  ip_address text,
  user_agent text
);

alter table if exists public.user_login_events
  add constraint user_login_events_provider_check
  check (provider in ('email', 'google'));

create index if not exists user_login_events_user_id_idx
  on public.user_login_events(user_id, login_at desc);

create index if not exists user_login_events_provider_idx
  on public.user_login_events(provider, login_at desc);

alter table if exists public.visitor_events
  add column if not exists user_id bigint references public.user_accounts(id) on delete set null;

create index if not exists visitor_events_user_id_idx
  on public.visitor_events(user_id, created_at desc);

create table if not exists public.user_taste_profiles (
  user_id bigint primary key references public.user_accounts(id) on delete cascade,
  taste_profile jsonb not null default '{}'::jsonb,
  source_session_ids text[] not null default '{}'::text[],
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists user_taste_profiles_updated_at_idx
  on public.user_taste_profiles(updated_at desc);
